name: Publish Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Framework-dependent (small, needs .NET runtime installed)
      - run: dotnet publish FileOrganizer.csproj -c Release -r win-x64 `
          -p:PublishSingleFile=true `
          -p:SelfContained=false `
          -p:AssemblyName=FileOrganizer-framework-dependent `
          -o publish/framework-dependent

      # Self-contained (large, includes runtime)
      - run: dotnet publish FileOrganizer.csproj -c Release -r win-x64 `
          -p:PublishSingleFile=true `
          -p:SelfContained=true `
          -p:AssemblyName=FileOrganizer-self-contained `
          -o publish/self-contained

      # Upload with versioned filenames
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/framework-dependent/FileOrganizer-framework-dependent.exe#FileOrganizer-${{ github.ref_name }}-framework-dependent.exe
            publish/self-contained/FileOrganizer-self-contained.exe#FileOrganizer-${{ github.ref_name }}-self-contained.exe
